version: '3.8'
services:
  stats-server:
    build: ./stats
    image: stats
    container_name: stats
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5433/stats
      - SPRING_DATASOURCE_USERNAME=stats
      - SPRING_DATASOURCE_PASSWORD=stats
      - SPRING_DATASOURCE_DRIVERCLASSNAME=org.postgresql.Driver

  stats-db:
    image: postgres:13
    container_name: stats-db
    expose:
      - "5433"
    ports:
      - "5433:5433"
    command: -p 5433
    environment:
      - POSTGRES_DB=stats
      - POSTGRES_USER=stats
      - POSTGRES_PASSWORD=stats

  ewm-service:
    build: ./server
    image: server
    container_name: server
    ports:
      - "8080:8080"
    depends_on:
      - server-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://server-db:5432/server
      - SPRING_DATASOURCE_USERNAME=server
      - SPRING_DATASOURCE_PASSWORD=server
      - STATS_SERVER_URL=http://stats-server:9090

  server-db:
    image: postgres:14
    container_name: server-db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=server
      - POSTGRES_USER=server
      - POSTGRES_PASSWORD=server
